In [41]:
import numpy as np

In [42]:
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [57]:
b = np.diff(a, axis = 1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [58]:
ones = np.ones(4).reshape(4, -1)

In [59]:
np.concatenate([b, ones], axis = 1)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [45]:
pp = np.ones(4).reshape(4, -1)
pp

array([[1.],
       [1.],
       [1.],
       [1.]])

In [46]:
ap = np.array([1,1,1,1]).reshape(4, -1)
ap

array([[1],
       [1],
       [1],
       [1]])

In [ ]:
np.concatenate([b, ap

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [47]:
type(np.ones(4))

numpy.ndarray

In [48]:
type(np.array([1,1,1,1]))

numpy.ndarray