In [1]:
import numpy as np
import pandas as pd

## 부분 데이터 꺼내기: 판다스를 왜 써야할까?

### 기본 인덱싱

`-` 기본 인덱싱

In [2]:
a = 'asdf'
a[2]

'd'

In [3]:
a[-1]

'f'

`-` 슬라이싱

In [4]:
a[1:3]

'sd'

In [5]:
a[:-2]

'as'

In [6]:
a[-2:]

'df'

`-` 스트라이딩

In [8]:
a = 'asdf'
a[::2]

'ad'

`-` 불가능한 것

In [9]:
a[[1,2]]

TypeError: string indices must be integers

In [10]:
a[[True, True, False, True]]

TypeError: string indices must be integers

### 팬시 인덱싱

In [12]:
a = np.arange(55, 61)
a

array([55, 56, 57, 58, 59, 60])

In [13]:
a[[1,2,-1]]

array([56, 57, 60])

In [16]:
a[[True, True, False, True, True, False]]

array([55, 56, 58, 59])

In [18]:
a < 58

array([ True,  True,  True, False, False, False])

In [19]:
a[a<58]

array([55, 56, 57])

### 2차원 자료형의 인덱싱

In [21]:
a = np.arange(4*3).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
a[0:2, 1]

array([1, 4])

`-` 차원을 유지하면서 인덱싱을 하고 싶으면?

In [26]:
a[0:2, [1]]

array([[1],
       [4]])

### Hash

`-` 예제1: (key,value)

In [29]:
d = {'att':65, 'rep':45, 'mid':30, 'fin':100}
d

{'att': 65, 'rep': 45, 'mid': 30, 'fin': 100}

In [30]:
d['att']

65

`-` 예제2: numpy와 비교

In [111]:
np.random.seed(43052)
att = np.random.choice(np.arange(10,21)*5,20)
rep = np.random.choice(np.arange(5,21)*5,20)
mid = np.random.choice(np.arange(0,21)*5,20)
fin = np.random.choice(np.arange(0,21)*5,20)
key = ['202212'+str(s) for s in np.random.choice(np.arange(300,501),20,replace=False)]
test_dic = {key[i] : {'att':att[i], 'rep':rep[i], 'mid':mid[i], 'fin':fin[i]} for i in range(20)}
test_ndarray = np.array([key,att,rep,mid,fin],dtype=np.int64).T

학번 '202212460'에 해당하는 학생의 출석점수를 알고 싶다면?

(풀이1) - Hash

In [32]:
test_dic['202212460']['att']

55

(풀이2) - 가독성이 떨어져

In [39]:
test_ndarray[:6]

array([[202212377,        65,        45,         0,        10],
       [202212473,        95,        30,        60,        10],
       [202212310,        65,        85,        15,        20],
       [202212460,        55,        35,        35,         5],
       [202212320,        80,        60,        55,        70],
       [202212329,        75,        40,        75,        85]],
      dtype=int64)

In [46]:
test_ndarray[test_ndarray[:,0] == 202212460, 1]

array([55], dtype=int64)

# pandas 개발동기

### 엑셀처럼 데이터를 테이블 형태로 정리하고 싶다.

In [47]:
np.random.seed(43052)
att = np.random.choice(np.arange(10,21)*5,20)
rep = np.random.choice(np.arange(5,21)*5,20)
mid = np.random.choice(np.arange(0,21)*5,20)
fin = np.random.choice(np.arange(0,21)*5,20)
key = ['202212'+str(s) for s in np.random.choice(np.arange(300,501),20,replace=False)]
test_dic = {key[i] : {'att':att[i], 'rep':rep[i], 'mid':mid[i], 'fin':fin[i]} for i in range(20)}

(풀이1)

In [50]:
pd.DataFrame(test_dic).T

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100
202212377   75   40  100   15
202212463   65   45   45   90
202212471   60   60   25    0
202212400   95   65   20   10
202212469   90   80   80   20
202212318   55   75   35   25
202212432   95   95   45    0
202212443   95   55   15   35
202212367   50   80   40   30
202212458   50   55   15   85
202212396   95   30   30   95
202212482   50   50   45   10
202212452   65   55   15   45
202212387   70   70   40   35
202212354   90   90   80   90

(방법2)

In [52]:
test_dic2 = {'att':{key[i]:att[i] for i in range(20)}, 
             'rep':{key[i]:rep[i] for i in range(20)},
             'mid':{key[i]:mid[i] for i in range(20)},
             'fin':{key[i]:fin[i] for i in range(20)}}

pd.DataFrame(test_dic2)

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100
202212377   75   40  100   15
202212463   65   45   45   90
202212471   60   60   25    0
202212400   95   65   20   10
202212469   90   80   80   20
202212318   55   75   35   25
202212432   95   95   45    0
202212443   95   55   15   35
202212367   50   80   40   30
202212458   50   55   15   85
202212396   95   30   30   95
202212482   50   50   45   10
202212452   65   55   15   45
202212387   70   70   40   35
202212354   90   90   80   90

(풀이3)

In [65]:
df = pd.DataFrame({'att':att, 'rep':rep, 'mid':mid, 'fin':fin}, index = key)
df[:5]

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100

In [66]:
df = pd.DataFrame({'att':att, 'rep':rep, 'mid':mid, 'fin':fin})
df[:5]

att  rep  mid  fin
0   65   55   50   40
1   95  100   50   80
2   65   90   60   30
3   55   80   75   80
4   80   30   30  100

In [68]:
df = pd.DataFrame({'key':key, 'att':att, 'rep':rep, 'mid':mid, 'fin':fin})
df[:5]

key  att  rep  mid  fin
0  202212380   65   55   50   40
1  202212370   95  100   50   80
2  202212363   65   90   60   30
3  202212488   55   80   75   80
4  202212312   80   30   30  100

In [89]:
df = pd.DataFrame({'att':att, 'rep':rep, 'mid':mid, 'fin':fin})
df.set_index([key], inplace = True)
df[:5]

att  rep  mid  fin
202212380   65   55   50   40
202212370   95  100   50   80
202212363   65   90   60   30
202212488   55   80   75   80
202212312   80   30   30  100

### 해싱으로 원하는 정보를 뽑고 싶다.

In [80]:
test_dic2['att']['202212380']

65

In [90]:
df['att']['202212380']

65

### 인덱싱으로 정보를 뽑고 싶다.(리스트나 넘파이처럼)

`-` 첫 번째 학생의 기말고사 성적을 출력

In [115]:
test_ndarray[0, -1]

40

In [100]:
df.iloc[0,-1]

40

`-` 홀수 번째 학생의 점수를 출력

In [116]:
test_ndarray[::2]

array([[202212380,        65,        55,        50,        40],
       [202212363,        65,        90,        60,        30],
       [202212312,        80,        30,        30,       100],
       [202212463,        65,        45,        45,        90],
       [202212400,        95,        65,        20,        10],
       [202212318,        55,        75,        35,        25],
       [202212443,        95,        55,        15,        35],
       [202212458,        50,        55,        15,        85],
       [202212482,        50,        50,        45,        10],
       [202212387,        70,        70,        40,        35]],
      dtype=int64)

In [117]:
df[::2]

att  rep  mid  fin
202212380   65   55   50   40
202212363   65   90   60   30
202212312   80   30   30  100
202212463   65   45   45   90
202212400   95   65   20   10
202212318   55   75   35   25
202212443   95   55   15   35
202212458   50   55   15   85
202212482   50   50   45   10
202212387   70   70   40   35

`-` 맨 끝에서 3명의 점수를 출력하고 싶다.

In [118]:
test_ndarray[-3:]

array([[202212452,        65,        55,        15,        45],
       [202212387,        70,        70,        40,        35],
       [202212354,        90,        90,        80,        90]],
      dtype=int64)

In [119]:
df.iloc[-3:]

att  rep  mid  fin
202212452   65   55   15   45
202212387   70   70   40   35
202212354   90   90   80   90

`-` 맨 끝에서 3명의 점수 중 마지막 2개의 칼럼만 출력하고 싶다.

In [124]:
test_ndarray[-3:, -2:]

array([[15, 45],
       [40, 35],
       [80, 90]], dtype=int64)

In [126]:
df.iloc[-3:, -2:]

mid  fin
202212452   15   45
202212387   40   35
202212354   80   90

### 궁극: 해싱과 인덱싱을 모두 지원하는 아주 우수한 자료형을 만들고 싶다.

`-` 중간고사 점수가 20점 이상이면서 동시에 출력점수가 60점 미만인 학생들의 기말고사 점수를 출력

(풀이1) 데이터베이스 스타일 - and, or, &, |

In [132]:
df.query('mid >= 20 and att < 60')['fin']

202212488    80
202212318    25
202212367    30
202212482    10
Name: fin, dtype: int32

(풀이2) numpy로 하려면? - 구현 난이도도 어렵고 가독성도 꽝이다.

In [146]:
test_ndarray[(test_ndarray[:, 4] >= 20) & (test_ndarray[:, 1] < 60), 4]

array([80, 25, 30, 85], dtype=int64)

`-` 중간고사 점수 < 기말고사 점수인 학생들의 출석 점수 평균을 출력

In [152]:
df.query('mid < fin')['att'].mean()

76.66666666666667

# pandas 사용법

## pandas 공부 1단계

### 데이터프레임 선언

#### "방법1: dictionary에서 만든다."

In [153]:
dic = {'att':[30,40,50], 'mid':[50,60,70]}
pd.DataFrame(dic)

att  mid
0   30   50
1   40   60
2   50   70

In [154]:
dic = {'att':(30,40,50), 'mid':(50,60,70)}
pd.DataFrame(dic)

att  mid
0   30   50
1   40   60
2   50   70

In [155]:
dic = {'att':np.array([30,40,50]), 'mid':np.array([50,60,70])}
pd.DataFrame(dic)

att  mid
0   30   50
1   40   60
2   50   70

#### "방법2: 2차원 ndarray에서 만든다."

In [156]:
nda = np.arange(2*3).reshape(2,3)
pd.DataFrame(nda)

0  1  2
0  0  1  2
1  3  4  5

### 열의 이름 부여

#### "방법1: 딕셔너리를 통하여 만들면 딕셔너리의 key가 자동으로 열의 이름이 된다."

In [157]:
dic = {'att':(30,40,50), 'mid':(50,60,70)}
pd.DataFrame(dic)

att  mid
0   30   50
1   40   60
2   50   70

#### "방법2: pd.DataFrame()의 옵션에 columns를 이용한다."

In [158]:
nda = np.arange(2*3).reshape(2,3)
pd.DataFrame(nda, columns=['X1', 'X2', 'X3'])

X1  X2  X3
0   0   1   2
1   3   4   5

#### "방법3: df.columns에 원하는 열 이름을 덮어쓴다."

In [160]:
nda = np.arange(2*3).reshape(2,3)
df = pd.DataFrame(nda)
df.columns = ['X1', 'X2', 'X3']
df

X1  X2  X3
0   0   1   2
1   3   4   5

In [161]:
nda = np.arange(2*3).reshape(2,3)
df = pd.DataFrame(nda)
df.columns = ['X1', 'X2', 'X3']
df

X1  X2  X3
0   0   1   2
1   3   4   5

#### "방법4: df.columns에 원하는 열 이름을 덮어쓴다.(2) - Recommend"

`-` 컴퓨터가 이해하기 좋다 (= 불필요한 에러를 방지할 수 있다.)

In [164]:
nda = np.arange(2*3).reshape(2,3)
df = pd.DataFrame(nda)
df.columns = pd.Index(['X1', 'X2', 'X3'])
df

X1  X2  X3
0   0   1   2
1   3   4   5

### 행의 이름 부여

#### "방법1: 중첩 dictionary이면 nested dic의 key가 행의 이름으로 된다."

In [165]:
pd.DataFrame({'att':{'guebin':30, 'iu':40, 'hynn':50} , 'mid':{'guebin':5, 'iu':45, 'hynn':90}})

att  mid
guebin   30    5
iu       40   45
hynn     50   90

#### "방법2: pd.DataFrame()의 index 옵션을 이용한다."

In [166]:
pd.DataFrame({'att':[30,40,50], 'mid':[5,45,90]}, index=['guebin', 'iu', 'hynn'])

att  mid
guebin   30    5
iu       40   45
hynn     50   90

#### "방법3: df.index에 원하는 행 이름을 덮어쓴다."

In [167]:
df=pd.DataFrame({'att':[30,40,50] , 'mid':[5,45,90]})
df

att  mid
0   30    5
1   40   45
2   50   90

In [169]:
df.index = pd.Index(['guebin', 'iu', 'hynn'])
df

att  mid
guebin   30    5
iu       40   45
hynn     50   90

#### "방법4: df.set_index()를 이용하여 덮어씌운다."

In [171]:
df=pd.DataFrame({'att':[30,40,50] , 'mid':[5,45,90]})
df

att  mid
0   30    5
1   40   45
2   50   90

In [172]:
df.set_index(pd.Index(['guebin', 'iu', 'hynn']))
df

att  mid
0   30    5
1   40   45
2   50   90

> Warning: 아래는 에러가 난다.

In [173]:
df.set_index(['guebin', 'iu', 'hynn'])
df

KeyError: "None of ['guebin', 'iu', 'hynn'] are in the columns"

`-` 아래는 가능하지만 추천하지 않는다. pd.Index로 통일하면 되는데 굳이 일관성 떨어지는 방법을 고수할 이유 없음

In [ ]:
df.set_index([['guebin', 'iu', 'hynn']])
df

### 자료형, len, shape

In [174]:
df = pd.DataFrame({'att':[30,40,50], 'mid':[5,45,90]})
df

att  mid
0   30    5
1   40   45
2   50   90

In [175]:
type(df)

pandas.core.frame.DataFrame

In [176]:
len(df)

3

In [177]:
df.shape

(3, 2)

`-` for문의 반복변수

In [186]:
for k in df:
    print(k) # 딕셔너

att
mid


In [187]:
for k in {'att':[30,40,50], 'mid':[5,45,90]}:
    print(k)

att
mid
