In [2]:
import numpy as np

In [3]:
data2 = np.load('test.npy')

In [9]:
data2

array([[ 229.80970389,  212.83914114],
       [ 230.51681067,  213.54624792],
       [ 206.47518011,  188.0904038 ],
       ...,
       [ 743.87633381, -155.56349186],
       [ 744.58344059, -154.85638508],
       [ 739.63369312, -161.22034611]])

In [10]:
data2[1:50, :]

array([[230.51681067, 213.54624792],
       [206.47518011, 188.0904038 ],
       [229.1025971 , 210.71782079],
       [229.80970389, 211.42492757],
       [230.51681067, 212.13203436],
       [231.22391745, 212.83914114],
       [231.93102423, 213.54624792],
       [227.68838354, 207.88939367],
       [228.39549032, 208.59650045],
       [229.1025971 , 209.30360723],
       [229.80970389, 210.01071401],
       [230.51681067, 210.71782079],
       [231.22391745, 211.42492757],
       [231.93102423, 212.13203436],
       [232.63813101, 212.83914114],
       [233.34523779, 213.54624792],
       [234.05234457, 214.2533547 ],
       [234.75945135, 214.96046148],
       [235.46655814, 215.66756826],
       [236.17366492, 216.37467504],
       [236.8807717 , 217.08178182],
       [237.58787848, 217.78888861],
       [226.98127676, 205.76807333],
       [227.68838354, 206.47518011],
       [228.39549032, 207.18228689],
       [229.1025971 , 207.88939367],
       [229.80970389, 208.59650045],
 

In [7]:
len(data2)

5513

In [8]:
print(data2)

[[ 229.80970389  212.83914114]
 [ 230.51681067  213.54624792]
 [ 206.47518011  188.0904038 ]
 ...
 [ 743.87633381 -155.56349186]
 [ 744.58344059 -154.85638508]
 [ 739.63369312 -161.22034611]]
